In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
array_a = np.array([1, 2, 3, 4])

In [6]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [7]:
array_a[0],array_b[-1],array_a[:2]

(1, 2.0, array([1, 2]))

In [8]:
array_a.dtype,array_b.dtype

(dtype('int32'), dtype('float64'))

In [9]:
empty_array=np.array([])
empty_array.dtype

dtype('float64')

In [10]:
np.array([1,2,3,4],dtype=np.float_)

array([1., 2., 3., 4.])

In [11]:
np.array([1,2,3,4],dtype=np.int8)


array([1, 2, 3, 4], dtype=int8)

In [12]:
array_c=np.array(["ada","lovelace"])

In [13]:
array_c.dtype

dtype('<U8')

#### Dimensions and shapes

In [14]:
my_array=np.array([
    [1,2,3],
    [4,5,6]
])

In [15]:
array_a.shape

(4,)

In [16]:
my_array.shape

(2, 3)

In [17]:
array_a.ndim

1

In [18]:
my_array.ndim

2

In [19]:
my_array.size

6

In [20]:
my_array2=np.array([
[ 
    [12,11,10],
    [9,8,7],
],
[
    [6,5,4],
    [3,2,1]
]
])

In [21]:
my_array2.ndim

3

In [22]:
my_array2.size

12

In [23]:
my_array2.shape

(2, 2, 3)

##### Indexing and slicing

In [24]:
my_array3=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [28]:
my_array3[1]

array([4, 5, 6])

In [29]:
my_array3[1][0]


4

In [30]:
my_array3[1,0]


4

In [31]:
my_array3[0:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
my_array3[:2,:2]


array([[1, 2],
       [4, 5]])

In [33]:
my_array3[1]=np.array([10,1,10])
my_array3



array([[ 1,  2,  3],
       [10,  1, 10],
       [ 7,  8,  9]])

In [35]:
my_array3[2]=99
my_array3



array([[ 1,  2,  3],
       [10,  1, 10],
       [99, 99, 99]])

In [36]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [41]:
my_array4=np.arange(0,10)
my_array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
my_array4.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
np.arange(1,10.1,4)

array([1., 5., 9.])

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((5,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [51]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
my_array=np.random.random((5,2))
my_array

array([[0.69516013, 0.67329937],
       [0.95922323, 0.51551499],
       [0.43228426, 0.14636268],
       [0.03936532, 0.82654748],
       [0.25947075, 0.05966093]])

In [59]:
my_array=np.random.randint(100,size=(5,5))
my_array


array([[93, 91, 23, 16, 33],
       [93, 81, 39, 45, 98],
       [27,  8, 51, 57, 14],
       [58, 82, 27, 79, 66],
       [60, 33,  5, 74, 14]])

In [61]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [62]:
#any(), all(), full(), concatenate()

In [65]:
array_1=np.arange(0,10)
array_1=array_1.reshape(2,5)
array_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
np.concatenate([array_1,array_1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
np.concatenate([array_1,array_1],axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

#### STATISTICS

In [25]:
array_1=np.arange(0,10)
array_1=array_1.reshape(2,5)
array_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
array_1.sum()

45

In [27]:
array_1.mean()

4.5

In [28]:
array_1.std()

2.8722813232690143

In [29]:
array_1.var()

8.25

In [30]:
array_1.sum(axis=1) #satırlar toplanıyor

array([10, 35])

In [31]:
array_1.sum(axis=0) #sutunlar toplanıyor


array([ 5,  7,  9, 11, 13])

In [32]:
array_1 +10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
array_2=np.arange(0,10)
array_2=array_2.reshape(5,2)
array_2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
array_2 +=10

In [35]:
array_2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

boolean arrays

In [36]:
a=np.arange(4)

In [37]:
a[0],a[-1]

(0, 3)

In [38]:
a[[0,-1]]

array([0, 3])

In [39]:
a[[True,False,False,True]]


array([0, 3])

In [40]:
a>=2

array([False, False,  True,  True])

In [41]:

a[a>=2]

array([2, 3])

In [42]:
a.mean()

1.5

In [43]:
a[a>a.mean()]

array([2, 3])

In [44]:
a[~(a>a.mean())]


array([0, 1])

In [45]:
a[(a==0)|(a==1)]


array([0, 1])

In [46]:
a[(a<=2)&(a%2==0)]


array([0, 2])

 - 100 kadar rastgele tamsayılardan oluşan 3,3 bir matris oluşturun.
 - 30'dan büyük olanları boolean yöntemmi ile filtrelein

In [52]:
my_array=np.random.randint(100,size=(3,3))
my_array

array([[67,  2, 14],
       [66, 29, 17],
       [60, 31,  5]])

In [53]:
boolean_array=my_array>30
boolean_array

array([[ True, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [55]:
my_array[boolean_array]

array([67, 66, 60, 31])

In [56]:
my_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = my_array.reshape(5,2)
array_2 = my_array.reshape(2,5)

In [57]:
array_1,array_2

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [59]:
np.dot(array_1, array_2) # 2 matrisin çarpımı

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [60]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [61]:
import sys

In [104]:
sys.getsizeof(10)

28

In [107]:
sys.getsizeof(1000**100)


160

In [108]:
np.dtype(int).itemsize

4

In [109]:
np.dtype(np.int8).itemsize


1

In [110]:
np.dtype(float).itemsize


8

In [111]:
sys.getsizeof([1,2,3])

88

In [65]:
my_list=list(range(100000))

In [66]:
my_arr=np.arange(100000)

In [67]:
np.array([1, 2, 3]).nbytes

12

In [68]:
%time np.sum(my_array ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


285

In [69]:
%time sum([number**2 for number in my_list])

CPU times: total: 46.9 ms
Wall time: 43.2 ms


333328333350000